# Generated by Django 2.2 on 2019-10-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191019_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('FW', 'Footwear'), ('AS', 'Accessories'), ('TR', 'Traditional'), ('PR', 'Perfumes')], max_length=2),
        ),
    ]
